/*
 * Copyright (C) 2024-2026 Aethel-Systems. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * Aethelium IM4P (Image4 Payload) 容器生成器
 * =========================================
 * 
 * IM4P 是 Apple 的 Image4 标准中用于 iBoot 的有效载荷容器。
 * 本模块直接从 Mach-O 二进制构造完整的 ASN.1 DER 编码 IM4P 容器。
 * 
 * IM4P 结构（ASN.1 语法）：
 * 
 * IM4P ::= SEQUENCE {
 *     magic       IA5String ("IM4P"),
 *     type        IA5String (identifier, e.g., "krnl"),
 *     description IA5String (generated by Aethelium),
 *     image       OCTET STRING (Mach-O 二进制)
 * }
 * 
 * 约束：
 * - 不使用任何外部工具（wimutil, img4tool 等）
 * - 纯手工 ASN.1 构造，无第三方库
 * - 完整的错误检查和边界验证
 * - Mach-O 可以是空的（iBoot 将自行处理）
 */

#ifndef AETHEL_IM4P_GENERATOR_H
#define AETHEL_IM4P_GENERATOR_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
   IM4P 生成器配置
   ============================================================================ */

typedef struct {
    /* 输入：Mach-O 二进制 */
    const uint8_t *macho_data;
    size_t macho_size;
    
    /* IM4P 标识 - 通常是 "krnl"（内核）或其他负载名 */
    const char *payload_identifier;  /* e.g., "krnl", "logo", "llb" */
    
    /* 输出文件名 */
    const char *output_file;
    
    /* 调试/日志 */
    int verbose;
} im4p_config_t;

/* ============================================================================
   公共接口函数
   ============================================================================ */

/**
 * im4p_generate - 从 Mach-O 二进制生成 IM4P 容器
 * 
 * 此函数执行完整的工作流：
 * 1. 验证输入参数
 * 2. 构造 ASN.1 树（IM4P 结构）
 * 3. DER 编码树
 * 4. 写出 .im4p 文件
 * 
 * 参数：
 *   output_file     - 输出 .im4p 文件路径
 *   macho_data      - Mach-O 二进制指针
 *   macho_size      - 大小（字节）
 *   identifier      - IM4P 标识（e.g., "krnl"）
 * 
 * 返回值：
 *   0               - 成功
 *   -1              - 参数验证失败
 *   -2              - 内存分配失败
 *   -3              - ASN.1 构造失败
 *   -4              - DER 编码失败
 *   -5              - 文件写入失败
 */
int im4p_generate(const char *output_file,
                 const uint8_t *macho_data,
                 size_t macho_size,
                 const char *identifier);

/**
 * im4p_container_create - 创建 IM4P 容器结构
 * 
 * 返回值：
 *   IM4P ASN.1 树的根节点，失败返回 NULL
 */
void* im4p_container_create(const uint8_t *macho_data,
                           size_t macho_size,
                           const char *identifier);

/**
 * im4p_container_encode - 将 IM4P 容器编码为 DER 二进制
 * 
 * 参数：
 *   container   - im4p_container_create 返回的容器
 *   output      - 输出缓冲区
 *   output_size - 输出缓冲区容量（会被更新为实际大小）
 * 
 * 返回值：
 *   0           - 成功
 *   -1          - 编码失败
 */
int im4p_container_encode(void *container, uint8_t *output, size_t *output_size);

/**
 * im4p_container_destroy - 销毁 IM4P 容器
 */
void im4p_container_destroy(void *container);

#ifdef __cplusplus
}
#endif

#endif /* AETHEL_IM4P_GENERATOR_H */
